# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3"

volumes:
  ordererdinuscom:
  orderer2dinuscom:
  orderer3dinuscom:
  orderer4dinuscom:
  orderer5dinuscom:
  peer0coe1dinuscom:
  peer0coe2dinuscom:
  peer0coe3dinuscom:
  peer0coe4dinuscom:

networks:
  test:
    external:
      name: test

services:
  ordererdinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer.dinus.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer.dinus.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer.dinus.com/tls/:/var/hyperledger/orderer/tls
      - ordererdinuscom:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      test:
        aliases:
          - orderer.dinus.com

  orderer2dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer2.dinus.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer2.dinus.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer2.dinus.com/tls/:/var/hyperledger/orderer/tls
      - orderer2dinuscom:/var/hyperledger/production/orderer
    ports:
      - 8050:7050
    networks:
      test:
        aliases:
          - orderer2.dinus.com

  orderer3dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer3.dinus.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer3.dinus.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer3.dinus.com/tls/:/var/hyperledger/orderer/tls
      - orderer3dinuscom:/var/hyperledger/production/orderer
    ports:
      - 9050:7050
    networks:
      test:
        aliases:
          - orderer3.dinus.com

  orderer4dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer4.dinus.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer4.dinus.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer4.dinus.com/tls/:/var/hyperledger/orderer/tls
      - orderer4dinuscom:/var/hyperledger/production/orderer
    ports:
      - 10050:7050
    networks:
      test:
        aliases:
          - orderer4.dinus.com

  orderer5dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer5.dinus.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer5.dinus.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/ordererOrganizations/dinus.com/orderers/orderer5.dinus.com/tls/:/var/hyperledger/orderer/tls
      - orderer5dinuscom:/var/hyperledger/production/orderer
    ports:
      - 11050:7050
    networks:
      test:
        aliases:
          - orderer5.dinus.com

  peer0coe1dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: peer0.coe1.dinus.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.coe1.dinus.com
      - CORE_PEER_ADDRESS=peer0.coe1.dinus.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.coe1.dinus.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.coe1.dinus.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coe1.dinus.com:7051
      - CORE_PEER_LOCALMSPID=Coe1Petani
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe1.dinus.com/peers/peer0.coe1.dinus.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe1.dinus.com/peers/peer0.coe1.dinus.com/tls:/etc/hyperledger/fabric/tls
      - peer0coe1dinuscom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      test:
        aliases:
          - peer0.coe1.dinus.com

  peer0coe2dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    container_name: peer0.coe2.dinus.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.coe2.dinus.com
      - CORE_PEER_ADDRESS=peer0.coe2.dinus.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.coe2.dinus.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coe2.dinus.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.coe2.dinus.com:9051
      - CORE_PEER_LOCALMSPID=Coe2Pengepul
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe2.dinus.com/peers/peer0.coe2.dinus.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe2.dinus.com/peers/peer0.coe2.dinus.com/tls:/etc/hyperledger/fabric/tls
      - peer0coe2dinuscom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      test:
        aliases:
          - peer0.coe2.dinus.com

  peer0coe3dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker2
    container_name: peer0.coe3.dinus.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.coe3.dinus.com
      - CORE_PEER_ADDRESS=peer0.coe3.dinus.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.coe3.dinus.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coe3.dinus.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.coe3.dinus.com:11051
      - CORE_PEER_LOCALMSPID=Coe3Distributor
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe3.dinus.com/peers/peer0.coe3.dinus.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe3.dinus.com/peers/peer0.coe3.dinus.com/tls:/etc/hyperledger/fabric/tls
      - peer0coe3dinuscom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      test:
        aliases:
          - peer0.coe3.dinus.com

  peer0coe4dinuscom:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker3
    container_name: peer0.coe4.dinus.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.coe4.dinus.com
      - CORE_PEER_ADDRESS=peer0.coe4.dinus.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.coe4.dinus.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coe4.dinus.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.coe4.dinus.com:13051
      - CORE_PEER_LOCALMSPID=Coe4Retailer
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe4.dinus.com/peers/peer0.coe4.dinus.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/coe4.dinus.com/peers/peer0.coe4.dinus.com/tls:/etc/hyperledger/fabric/tls
      - peer0coe4dinuscom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 13051:13051
    networks:
      test:
        aliases:
          - peer0.coe4.dinus.com
