# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3"

networks:
  test:
    external:
      name: test

services:
  ca_coe1:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coe1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/coe1:/etc/hyperledger/fabric-ca-server
    container_name: ca_coe1
    networks:
       test:
         aliases:
          - ca.coe1.dinus.com

  ca_coe2:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coe2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/coe2:/etc/hyperledger/fabric-ca-server
    container_name: ca_coe2
    networks:
       test:
         aliases:
          - ca.coe2.dinus.com

  ca_coe3:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker2
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coe3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/coe3:/etc/hyperledger/fabric-ca-server
    container_name: ca_coe3
    networks:
       test:
         aliases:
          - ca.coe3.dinus.com

  ca_coe4:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker3
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coe4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/coe4:/etc/hyperledger/fabric-ca-server
    container_name: ca_coe4
    networks:
       test:
         aliases:
          - ca.coe4.dinus.com

  ca_orderer:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
       test:
         aliases:
          - ca.orderer.dinus.com
